### ISSUE TITLE
切换测试记录时,页面乱码嘞

### ISSUE THREAD

**Issue by hibobo** [githublitao/HTMLTestRunner_Chart#1]
切换测试记录时,页面乱码嘞

**Comment by hibobo** [comment]
data_json = str(data_json) 改
data_json = json.dumps(data_json, encoding='utf-8', ensure_ascii=False)

**Comment by host452b** [comment]
谢谢 解决了我的问题~

**Comment by host452b** [comment]
import json
data_json = str(data_json) 改
data_json = json.dumps(data_json, encoding='utf-8', ensure_ascii=False)
