### ISSUE TITLE
谷歌浏览器查看历史报告出现中文乱码

### ISSUE THREAD

**Issue by OiAnthony** [githublitao/HTMLTestRunner_Chart#10]
谷歌浏览器查看历史报告出现中文乱码
![image](https://user-images.githubusercontent.com/62509433/87220971-1baea900-c39b-11ea-94f8-86fd2aacea84.png)

**Comment by name-jiang** [comment]
json文件编码格式不正确，修改成UTF-8试试

**Comment by alindas** [comment]
> json文件编码格式不正确，修改成UTF-8试试
一开始看到VS Code 显示的UTF8的编码格式的，以为它应该就是那个格式，没想到还是得手动改变一下编码才行LOL
