### ISSUE TITLE
历史走趋展示不出来

### ISSUE THREAD

**Issue by zhaiworld** [githublitao/HTMLTestRunner_Chart#2]
****
![image](https://user-images.githubusercontent.com/4532011/46787667-d646ed00-cd6a-11e8-9f77-920364449754.png)
![image](https://user-images.githubusercontent.com/4532011/46787696-eb238080-cd6a-11e8-839f-ed6651c3e79a.png)
@githublitao

**Comment by githublitao** [comment]
不支持远程url访问

**Comment by saberalexpan** [comment]
> 不支持远程url访问

同样问题，我本地也无法显示啊，url是这样的：`http://localhost:63342/ApiTesting/TestCases/reports/2018-12-24_14_14_04.html?_ijt=acidlkkfpecnigliil71cn5bel`
同样也是上面两个报错 @githublitao

**Comment by tyy02** [comment]
直接用浏览器打开报告文件就可以了

**Comment by ParsonHong** [comment]
大神  历史趋势图需要配置什么吗？在本地打开报告文件，没有趋势图
