### ISSUE TITLE
历史曲线图只能展示本次的，之前的展示不出来，需要怎么配置？能给个说明吗？

### ISSUE THREAD

**Issue by xiongye105554598** [githublitao/HTMLTestRunner_Chart#6]
历史曲线图只能展示本次的，之前的展示不出来，需要怎么配置？能给个说明吗？

**Comment by xiongye105554598** [comment]
![image](https://user-images.githubusercontent.com/54013289/63319285-1fcd7480-c34c-11e9-97d2-6c9941080ecc.png)

**Comment by githublitao** [comment]
生成的报告使用同一个文件名
