### ISSUE TITLE
查看第一次的报告是中文，切换到下一次的报告就乱码了

### ISSUE THREAD

**Issue by 947612227** [githublitao/HTMLTestRunner_Chart#8]
使用的是python3.4，浏览器火狐

![image](https://user-images.githubusercontent.com/39144531/70056656-ca755480-1616-11ea-96c9-45394938a627.png)

**Comment by 947612227** [comment]
解决办法
将文件中第209行和1124行
或者直接搜索gbk 全部替换为utf-8即可
line 209 
<script type="text/javascript" src="%(jsonpath)s" charset="utf-8"></script>
line 1124
description["title"] = title.encode("utf-8")
                    description["status"] = heading[2][1].encode("utf-8")
                    description["desc"] = desc.encode("utf-8")
                    description["data"] = data.encode("utf-8")

**Comment by githublitao** [comment]
谢谢提供
