### ISSUE TITLE
如果测试用例本身有问题，则HTMLTestRunner_Chart脚本会抛异常。

### ISSUE THREAD

**Issue by chenyaotie** [githublitao/HTMLTestRunner_Chart#9]
首先感谢作者的分享，给了我很大帮助，我在使用者发现一个地方貌似有问题
![image](https://user-images.githubusercontent.com/23055257/71439997-c8467780-2736-11ea-9feb-0b692cacd778.png)
定位发现，如果上面的用例已经抛异常了，那么在doc = t._testMethodDoc or '' 这行
这里的t 是一个ERROR类型，是没有_testMethodDoc属性的，因此回导致最终执行失败。
![image](https://user-images.githubusercontent.com/23055257/71440242-88cc5b00-2737-11ea-8410-9da19c04c910.png)
将此处异常捕获后，即可生成报告

**Comment by githublitao** [comment]
谢谢提供
